# targets
all: kvm-virt-and-libvirt-rootconf-2012.pp.pdf
# handout: sample.handout.pdf
# notes: sample.notes.pdf
# sample.text.pdf -- don't build article version by default

TEXINPUTS=.:$(RHBEAMER):
export TEXINPUTS

# path to rh beamer
RHBEAMER=..

# common tex makefile
include $(RHBEAMER)/Makefile.common
